version: '3.9'

services:

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  db:
    container_name: postgres
    image: postgres:15-alpine
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    restart: always

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./dockerfiles/dev/django/Dockerfile
    volumes:
      - ./core:/app
      - static_volumes:/app/static
      - media_volumes:/app/media
    working_dir: /app
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    expose:
      - "8000"
    environment:
      - DEBUG=False
    env_file:
      - ./envs/dev/django/.env
    restart: always
    depends_on:
      - db
      - redis

  celery:
    build:
      dockerfile: ./dockerfiles/dev/django/Dockerfile
    command: celery -A core worker --loglevel=info
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - backend

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volumes:/home/app/static
      - media_volumes:/home/app/media
    depends_on:
      - backend
      - redis
    restart: always

volumes:
  static_volumes:
  media_volumes:
